<?php

namespace ContainerZIb0nQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7ShMUGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I7ShMUG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I7ShMUG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'marineCoverageRepository' => ['privates', 'App\\Repository\\MarineCoverageRepository', 'getMarineCoverageRepositoryService', true],
        ], [
            'marineCoverageRepository' => 'App\\Repository\\MarineCoverageRepository',
        ]);
    }
}
