<?php

namespace ContainerZIb0nQ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F5lUhMlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F5lUhMl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F5lUhMl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardPlay' => ['privates', 'App\\Card\\CardPlay', 'getCardPlayService', true],
            'cardPoints' => ['privates', 'App\\Card\\CardPoints', 'getCardPointsService', true],
        ], [
            'cardPlay' => 'App\\Card\\CardPlay',
            'cardPoints' => 'App\\Card\\CardPoints',
        ]);
    }
}
