<?php

namespace ContainerLf211xu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OdF7kRXService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.odF7kRX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.odF7kRX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\MarineCoverageRepository', 'getMarineCoverageRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\MarineCoverageRepository',
        ]);
    }
}
