<?php

namespace ContainerLf211xu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardPlayService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Card\CardPlay' shared autowired service.
     *
     * @return \App\Card\CardPlay
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Card/CardPlay.php';

        return $container->privates['App\\Card\\CardPlay'] = new \App\Card\CardPlay();
    }
}
