<?php

namespace ContainerLS4kCqe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Jg0QfpService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.7Jg0Qfp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Jg0Qfp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cardGraphic' => ['privates', 'App\\Card\\CardGraphic', 'getCardGraphicService', true],
        ], [
            'cardGraphic' => 'App\\Card\\CardGraphic',
        ]);
    }
}
