<?php

namespace ContainerLS4kCqe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDrawCardControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\DrawCardController' shared autowired service.
     *
     * @return \App\Controller\DrawCardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DrawCardController.php';

        $container->services['App\\Controller\\DrawCardController'] = $instance = new \App\Controller\DrawCardController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\DrawCardController', $container));

        return $instance;
    }
}
