<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLS4kCqe\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLS4kCqe/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLS4kCqe.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLS4kCqe\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLS4kCqe\App_KernelTestDebugContainer([
    'container.build_hash' => 'LS4kCqe',
    'container.build_id' => '99cbfd0f',
    'container.build_time' => 1716377506,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLS4kCqe');
