<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFg8xACN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFg8xACN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFg8xACN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFg8xACN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFg8xACN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fg8xACN',
    'container.build_id' => 'b73fceb0',
    'container.build_time' => 1716378386,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFg8xACN');
