<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.05dacd30.js',
                'build/app.652303d0.js',
            ],
            'css' => [
                'build/app.213c5602.css',
            ],
        ],
    ],
],

]];
